states = {'east_azerbaijan':'آذربایجان شرقی',
          'west_azerbaijan':'آذربایجان غربی',
          'ardabil':'اردبیل',
          'isfahan':'اصفهان',
          'alborz':'البرز',
          'ilam':'ایلام',
          'bushehr':'بوشهر',
          'tehran':'تهران',
          'chaharmahal_and_bakhtiari':'چهارمحال و بختیاری',
          'south_khorasan':'خراسان جنوبی',
          'razavi_khorasan':'خراسان رضوی',
          'north_khorasan':'خراسان شمالی',
          'khuzestan':'خوزستان',
          'zanjan':'زنجان',
          'semnan':'سمنان',
          'sistan_and_baluchestan':'سیستان و بلوچستان',
          'fars':'فارس',
          'qazvin':'قزوین',
          'qom':'قم',
          'kurdistan':'کردستان',
          'kerman':'کرمان',
          'kermanshah':'کرمانشاه',
          'kohgiluyeh_and_boyer_ahmad':'کهگیلویه و بویراحمد',
          'golestan':'گلستان',
          'gilan':'گیلان',
          'lorestan':'لرستان',
          'mazandaran':'مازندران',
          'markazi':'مرکزی',
          'hormozgan':'هرمزگان',
          'hamadan':'همدان',
          'yazd':'یزد'}
i = 1
for state, state_name in states.items():
    print(f'<label>\n  <input type="checkbox" name="province{i}" value="{state}">{state_name}\n</label>')
    i += 1
